server:
  port: 51700
turbine:
  cluster-name-expression: new String('default')
  app-config: anan-zuulgateway
spring:
  boot:
    admin:
      context-path: /sba
      ui:
        #        favicon-danger: "assets/img/favicon-danger.png"
        #        favicon: "assets/img/favicon.png"
        title: "服务指标监控"
      #        public-url:
      #      instance-proxy:
      #        ignored-headers: "Cookie", "Set-Cookie", "Authorization"
      #      probed-endpoints: "health", "env", "metrics", "httptrace:trace", "threaddump:dump", "jolokia", "info", "logfile", "refresh", "flyway", "liquibase", "heapdump", "loggers", "auditevents"
      notify:
        mail:
          additional-properties:
          from: "Spring Boot Admin <noreply@localhost>"
          cc:
          to: "28860823@qq.com"
          template: "classpath:/META-INF/spring-boot-admin-server/mail/status-changed.html"
          ignore-changes: "UNKNOWN:UP"
          enabled: true
